import React, { useState } from "react";
import Head from "next/head";
import Swal from "sweetalert2";
import withReactContent from "sweetalert2-react-content";
import axios from "axios";

const Detail = () => {
    const requestURL = "http://127.0.0.1:5000/user_search/";
    // let getData;
    const MySwal = withReactContent(Swal);

    const [user, setUser] = useState({
        instituteName: "",
    });

    const [getData, setGetData] = useState();

    let name, value;

    const handleInputs = (e) => {
        // console.log(e);
        name = e.target.name;
        value = e.target.value;


        setUser({ ...user, [name]: value });
    };

    let nirf = ``;

    const postData = async (e) => {
        e.preventDefault();

        const { instituteName } = user;

        if (!instituteName) {
            MySwal.fire({
                icon: "error",
                title: <p>Error!</p>,
                text: "Please search something",
            });
        } else {
            // fetch data from beckend
            const options = {
                method: "POST",
                url: requestURL,
                data: user,
            };
            let data;
            MySwal.fire({
                title: "Please Wait",
                text: "Loading...",
                timerProgressBar: true,
                didOpen: () => {
                    Swal.showLoading();
                },
            });
            await axios
                .request(options)
                .then(function (response) {
                    data = response.data;
                    setGetData(response.data);
                    console.log(response.data);
                })
                .catch(function (error) {
                    console.error(error);
                });

            if (data) {
                MySwal.fire({
                    icon: "success",
                    title: <p>Success!</p>,
                    text: "Data Fetched Successfully",
                });
            } else {
                MySwal.fire({
                    icon: "error",
                    title: <p>Error!</p>,
                    text: "Data Not Found",
                });
            }


            setGetData(data);

            console.log(getData);
        }
    };

    return (
        <div className="modal modal-signin position-static d-block bg-none py-5">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="modal-dialog">
                <div className="modal-content bordeer border-0 rounded-4 shadow">
                    <div className="modal-header p-5 pb-4 border-bottom-0">
                        <h2 className="fw-bold mb-0">Search details...</h2>
                    </div>
                    <div className="modal-body p-5 pt-0">
                        <form className="">
                            <div className="form-floating mb-3">
                                <input
                                    type="name"
                                    className="form-control rounded-3"
                                    placeholder="name"
                                    name="instituteName"
                                    autoComplete="off"
                                    value={user.instituteName}
                                    onChange={handleInputs}
                                />
                                <label htmlFor="floatingInput">
                                    Institute name
                                </label>
                            </div>

                            <button
                                className="w-100 mb-2 btn btn-lg rounded-3 btn-primary"
                                type="submit"
                                onClick={postData}
                            >
                                Search
                            </button>
                        </form>
                    </div>
                </div>
            </div>

            <div className="modal-dialog">
                <div className="modal-content bordeer border-0 rounded-4 shadow">
                    <div className="modal-header p-5 pb-4 border-bottom-0">
                        <h2 className="fw-bold mb-0">
                            {getData
                                ? getData.instituteName
                                : "Search somthing..."}
                        </h2>
                    </div>
                    <div className="modal-body p-5 pt-0">
                        {getData ? (
                            <>
                                <table className="p-5">
                                    <tbody>
                                        <tr>
                                            <td className="pr-2">
                                                {" "}
                                                NAAC Grade
                                            </td>
                                            <td className="px-2"> : </td>
                                            <td className="px-2">
                                                {getData.NAAC}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td className="pr-2"> NAAC CGPA</td>
                                            <td className="px-2"> : </td>
                                            <td className="px-2">
                                                {getData.CGPA}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td className="pr-2"> NBA Rank</td>
                                            <td className="px-2"> : </td>
                                            <td className="px-2">
                                                {getData.NBA}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div className="mt-5">
                                    <h6 className="fw-bold mb-0">NIRF Rank</h6>
                                    {getData.NIRF.map((e) => {
                                        e.name;
                                        e.rank;
                                    })}
                                </div>
                            </>
                        ) : (
                            ""
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Detail;
