import React from "react";
import { Container } from "react-bootstrap";
import Form from "react-bootstrap/Form";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import DetailTable from "./DetailTable";
import Head from "next/head";

const Showrank = () => {
    return (
        <Container className="my-5">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            s
            <Form.Group
                as={Row}
                className="mb-3"
                controlId="search"
                style={{ width: "28rem" }}
            >
                <Form.Label column sm="2">
                    Search
                </Form.Label>
                <Col sm="10">
                    <Form.Control placeholder="Enter institute name" />
                </Col>
            </Form.Group>
            <DetailTable />
        </Container>
    );
};

export default Showrank;
